name: auto-version-tag
on:
  push:
    branches: [main, feature/async]
jobs:
  test:
    uses: ./.github/workflows/_test.yml
  tag:
    runs-on: ubuntu-22.04
    needs: test
    if: ${{ !contains(github.event.head_commit.message, '!skip-auto-tag') }}
    steps:
      - name: âœ… Repository checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: âš™ï¸ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json
      - name: ğŸ“ Create and push new tag
        run: ./build.sh CreateVersionTag
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
    environment: allow-push-tag
env:
  NUKE_NO_LOGO: true
