name: auto-version-tag
on:
  workflow_run:
    workflows: main
    branches:
      - master
      - feature/async
    types: completed
jobs:
  tag:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' && !contains(github.event.workflow_run.head_commit.message, '!skip-auto-tag') }}
    steps:
      - name: âœ… Repository checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: ğŸ“ Create and push new tag
        run: ./build.sh CreateVersionTag
        env:
          GITHUB_TOKEN: ${{ github.token }}
    permissions:
      contents: write
env:
  NUKE_NO_LOGO: true
